CREATE TABLE IF NOT EXISTS ENDRECO (ID int AUTO_INCREMENT PRIMARY KEY, RUA varchar (255), NUMERO VARCHAR(50), CIDADE varchar(255), ESTADO varchar(255));

CREATE TABLE IF NOT EXISTS PACIENTE (ID iNT AUTO_INCREMENT PRIMARY KEY, NOME VARCHAR(255), SOBRENOME VARCHAR 255, RG VARCHAR (255), DATA_CADASTRO TIMESTAMP WITHOUT TIME ZONE, ENDERECO_ID INT);