version: '3'
services:
  meuprimeirogrupocontainer:
    image: nomeimagem
    container_name: containercomminhaaplicacao
    build:
      context: .
    #volumes:


    #  - .\site:/usr/share/nginx/htm
    #volumes:
    #  - site:/usr/share/nginx/htm
    ports:
      - "8001:8080"
    networks:
      - placaservidor

networks:
  placaservidor:
    driver: bridge

    #volumes:
    #  site:

    # docker-compose up -d
    #mvn install
    #./mvnw clean package -DskipTests